version: '3.9'
services:

  app:
    container_name: ${COMPOSE_PROJECT_NAME}-app
    image: node:16-buster
    command: sh -c "yarn && yarn dev"
    expose:
      - 3000
    working_dir: /var/www/app
    volumes:
      - ./:/var/www/app
    networks:
      - network-dev

networks:
  network-dev: {}
