version: '3.9'
services:

  app:
    container_name: ${COMPOSE_PROJECT_NAME}-app
    image: node:16-buster
    command: sh -c "yarn && yarn generate && chown -R 1337:1337 /var/www/app/"
    working_dir: /var/www/app
    volumes:
      - ./:/var/www/app
    networks:
      - network-test

networks:
  network-test: {}
